#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

# FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
# WORKDIR /app
# EXPOSE 80

# FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build

# WORKDIR /src
# COPY */*.csproj /src
# RUN dotnet restore
# COPY . .
# WORKDIR "/src/Asp.netCoreMVCCRUD"
# RUN dotnet build "Asp.netCoreMVCCRUD.csproj" -c Release -o /app/buil

# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build-env

WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY ./ ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Asp.netCoreMVCCRUD.dll"]