# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: jetcipher/circleci-dotnet-core:2.2
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: Asp.netCoreMVCCRUD
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: Asp.netCoreMVCCRUD
      
      - run:
          name: Build and push Docker image
          command: |
            docker build -t MyProject .
            docker login -u nneka234 --password-Okwuchi12345
            docker tag registry.heroku.com/dotnet-core-crud-app/web
            heroku container:push web -a registry.heroku.com/dotnet-core-crud-app/web
            heroku container:release web -a registry.heroku.com/dotnet-core-crud-app/web
